game_data = {
    "wordle_index": 1677,
    "turn_number": 1,
    "guessed_words": ["SWEAR"],
    "players": ["KamronP23"],
    "schema": '<img src="./wordle/tiles/green/S.svg" width="40" /><img src="./wordle/tiles/yellow/W.svg" width="40" /><img src="./wordle/tiles/grey/E.svg" width="40" /><img src="./wordle/tiles/grey/A.svg" width="40" /><img src="./wordle/tiles/grey/R.svg" width="40" /><br/>',
    "letter_schema": [
        '<img src="./wordle/letters/white/Q.svg" width="20" />',
        '<img src="./wordle/letters/yellow/W.svg" width="20" />',
        '<img src="./wordle/letters/grey/E.svg" width="20" />',
        '<img src="./wordle/letters/grey/R.svg" width="20" />',
        '<img src="./wordle/letters/white/T.svg" width="20" />',
        '<img src="./wordle/letters/white/Y.svg" width="20" />',
        '<img src="./wordle/letters/white/U.svg" width="20" />',
        '<img src="./wordle/letters/white/I.svg" width="20" />',
        '<img src="./wordle/letters/white/O.svg" width="20" />',
        '<img src="./wordle/letters/white/P.svg" width="20" />',
        "<br />",
        '<img src="./wordle/letters/grey/A.svg" width="20" />',
        '<img src="./wordle/letters/green/S.svg" width="20" />',
        '<img src="./wordle/letters/white/D.svg" width="20" />',
        '<img src="./wordle/letters/white/F.svg" width="20" />',
        '<img src="./wordle/letters/white/G.svg" width="20" />',
        '<img src="./wordle/letters/white/H.svg" width="20" />',
        '<img src="./wordle/letters/white/J.svg" width="20" />',
        '<img src="./wordle/letters/white/K.svg" width="20" />',
        '<img src="./wordle/letters/white/L.svg" width="20" />',
        "<br />",
        '<img src="./wordle/letters/white/Z.svg" width="20" />',
        '<img src="./wordle/letters/white/X.svg" width="20" />',
        '<img src="./wordle/letters/white/C.svg" width="20" />',
        '<img src="./wordle/letters/white/V.svg" width="20" />',
        '<img src="./wordle/letters/white/B.svg" width="20" />',
        '<img src="./wordle/letters/white/N.svg" width="20" />',
        '<img src="./wordle/letters/white/M.svg" width="20" />',
    ],
}
