game_data = {
    "wordle_index": 145,
    "turn_number": 1,
    "guessed_words": ["LATTE"],
    "players": ["jordan-bott"],
    "schema": '<img src="./wordle/tiles/yellow/L.svg" width="40" /><img src="./wordle/tiles/green/A.svg" width="40" /><img src="./wordle/tiles/grey/T.svg" width="40" /><img src="./wordle/tiles/grey/T.svg" width="40" /><img src="./wordle/tiles/yellow/E.svg" width="40" /><br/>',
    "letter_schema": [
        '<img src="./wordle/letters/white/Q.svg" width="20" />',
        '<img src="./wordle/letters/white/W.svg" width="20" />',
        '<img src="./wordle/letters/yellow/E.svg" width="20" />',
        '<img src="./wordle/letters/white/R.svg" width="20" />',
        '<img src="./wordle/letters/grey/T.svg" width="20" />',
        '<img src="./wordle/letters/white/Y.svg" width="20" />',
        '<img src="./wordle/letters/white/U.svg" width="20" />',
        '<img src="./wordle/letters/white/I.svg" width="20" />',
        '<img src="./wordle/letters/white/O.svg" width="20" />',
        '<img src="./wordle/letters/white/P.svg" width="20" />',
        "<br />",
        '<img src="./wordle/letters/green/A.svg" width="20" />',
        '<img src="./wordle/letters/white/S.svg" width="20" />',
        '<img src="./wordle/letters/white/D.svg" width="20" />',
        '<img src="./wordle/letters/white/F.svg" width="20" />',
        '<img src="./wordle/letters/white/G.svg" width="20" />',
        '<img src="./wordle/letters/white/H.svg" width="20" />',
        '<img src="./wordle/letters/white/J.svg" width="20" />',
        '<img src="./wordle/letters/white/K.svg" width="20" />',
        '<img src="./wordle/letters/yellow/L.svg" width="20" />',
        "<br />",
        '<img src="./wordle/letters/white/Z.svg" width="20" />',
        '<img src="./wordle/letters/white/X.svg" width="20" />',
        '<img src="./wordle/letters/white/C.svg" width="20" />',
        '<img src="./wordle/letters/white/V.svg" width="20" />',
        '<img src="./wordle/letters/white/B.svg" width="20" />',
        '<img src="./wordle/letters/white/N.svg" width="20" />',
        '<img src="./wordle/letters/white/M.svg" width="20" />',
    ],
}
