lifetime_data = {
    "moves_made": 23,
    "games_played": 4,
    "players": 4,
    "wins": 4,
    "loses": 0,
    "invalid_guesses": 0,
    "words_guessed": {
        "UNDER": 1,
        "QUEER": 1,
        "QUITE": 1,
        "QUICK": 1,
        "CRANE": 1,
        "FEARS": 1,
        "BLEAK": 1,
        "EASEL": 1,
        "PLANT": 3,
        "TALLY": 1,
        "LATTE": 1,
        "LATHE": 1,
        "SNORE": 1,
        "BUNCH": 1,
        "FINCH": 1,
        "GHOST": 1,
        "WORST": 1,
        "FOIST": 1,
        "BOOST": 1,
        "COEST": 1,
        "JOUST": 1,
    },
    "wordle_words": ["EASEL", "LATHE", "FINCH", "JOUST"],
}
