lifetime_data = {
    "moves_made": 31,
    "games_played": 5,
    "players": 6,
    "wins": 4,
    "loses": 1,
    "invalid_guesses": 1,
    "words_guessed": {
        "UNDER": 1,
        "QUEER": 1,
        "QUITE": 1,
        "QUICK": 1,
        "CRANE": 1,
        "FEARS": 1,
        "BLEAK": 1,
        "EASEL": 1,
        "PLANT": 3,
        "TALLY": 1,
        "LATTE": 1,
        "LATHE": 1,
        "SNORE": 1,
        "BUNCH": 1,
        "FINCH": 1,
        "GHOST": 1,
        "WORST": 1,
        "FOIST": 1,
        "BOOST": 1,
        "COEST": 1,
        "JOUST": 1,
        "ADIEU": 1,
        "LASER": 1,
        "WATER": 1,
        "CATER": 1,
        "HATER": 1,
        "MATER": 1,
        "SWEAR": 1,
        "SPOOL": 1,
    },
    "wordle_words": ["EASEL", "LATHE", "FINCH", "JOUST", "EATER"],
}
