new_letter_schmea = [
    '<img src="./wordle/letters/white/Q.svg" width="20" />',
    '<img src="./wordle/letters/white/W.svg" width="20" />',
    '<img src="./wordle/letters/white/E.svg" width="20" />',
    '<img src="./wordle/letters/white/R.svg" width="20" />',
    '<img src="./wordle/letters/white/T.svg" width="20" />',
    '<img src="./wordle/letters/white/Y.svg" width="20" />',
    '<img src="./wordle/letters/white/U.svg" width="20" />',
    '<img src="./wordle/letters/white/I.svg" width="20" />',
    '<img src="./wordle/letters/white/O.svg" width="20" />',
    '<img src="./wordle/letters/white/P.svg" width="20" />',
    "<br /> &ensp;",
    '<img src="./wordle/letters/white/A.svg" width="20" />',
    '<img src="./wordle/letters/white/S.svg" width="20" />',
    '<img src="./wordle/letters/white/D.svg" width="20" />',
    '<img src="./wordle/letters/white/F.svg" width="20" />',
    '<img src="./wordle/letters/white/G.svg" width="20" />',
    '<img src="./wordle/letters/white/H.svg" width="20" />',
    '<img src="./wordle/letters/white/J.svg" width="20" />',
    '<img src="./wordle/letters/white/K.svg" width="20" />',
    '<img src="./wordle/letters/white/L.svg" width="20" />',
    "<br /> &ensp; &ensp;",
    '<img src="./wordle/letters/white/Z.svg" width="20" />',
    '<img src="./wordle/letters/white/X.svg" width="20" />',
    '<img src="./wordle/letters/white/C.svg" width="20" />',
    '<img src="./wordle/letters/white/V.svg" width="20" />',
    '<img src="./wordle/letters/white/B.svg" width="20" />',
    '<img src="./wordle/letters/white/N.svg" width="20" />',
    '<img src="./wordle/letters/white/M.svg" width="20" />',
]
