player_data = {
    "jordan-bott": {
        "total_moves": 15,
        "total_winning_moves": 2,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-10",
        "most_recent_move": "2024-03-11",
        "guess_history": {
            "UNDER": 1,
            "QUEER": 1,
            "QUITE": 1,
            "QUICK": 1,
            "CRANE": 1,
            "FEARS": 1,
            "PLANT": 3,
            "TALLY": 1,
            "LATTE": 1,
            "LATHE": 1,
            "SNORE": 1,
            "BUNCH": 1,
            "FINCH": 1,
        },
    },
    "IanKBovard": {
        "total_moves": 2,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-10",
        "most_recent_move": "2024-03-10",
        "guess_history": {"BLEAK": 1, "EASEL": 1},
    },
    "daisukev": {
        "total_moves": 5,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-11",
        "most_recent_move": "2024-03-11",
        "guess_history": {"GHOST": 1, "WORST": 1, "FOIST": 1, "BOOST": 1, "JOUST": 1},
    },
    "7ingyu": {
        "total_moves": 1,
        "total_winning_moves": 0,
        "total_invalid_guesses": 1,
        "first_move_made": "2024-03-11",
        "most_recent_move": "2024-03-11",
        "guess_history": {"COEST": 1},
    },
    "emilyvictany": {
        "total_moves": 4,
        "total_winning_moves": 0,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-11",
        "most_recent_move": "2024-03-11",
        "guess_history": {"ADIEU": 1, "LASER": 1, "WATER": 1, "CATER": 1},
    },
}
