player_data = {
    "jordan-bott": {
        "total_moves": 39,
        "total_winning_moves": 6,
        "total_invalid_guesses": 3,
        "first_move_made": "2024-03-10",
        "most_recent_move": "2024-03-20",
        "guess_history": {
            "UNDER": 1,
            "QUEER": 1,
            "QUITE": 1,
            "QUICK": 2,
            "CRANE": 4,
            "FEARS": 1,
            "PLANT": 4,
            "TALLY": 1,
            "LATTE": 2,
            "LATHE": 1,
            "SNORE": 1,
            "BUNCH": 1,
            "FINCH": 1,
            "SPOOL": 1,
            "SCOWL": 1,
            "RHYME": 1,
            "HAIRY": 1,
            "BERRY": 1,
            "DIRTY": 1,
            "GIRLY": 1,
            "MOTEL": 1,
            "APPLE": 1,
            "LABEL": 1,
            "BAGEL": 1,
            "SNOWY": 1,
            "FLICK": 1,
            "BRICK": 1,
            "CHICK": 1,
        },
    },
    "IanKBovard": {
        "total_moves": 2,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-10",
        "most_recent_move": "2024-03-10",
        "guess_history": {"BLEAK": 1, "EASEL": 1},
    },
    "daisukev": {
        "total_moves": 5,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-11",
        "most_recent_move": "2024-03-11",
        "guess_history": {"GHOST": 1, "WORST": 1, "FOIST": 1, "BOOST": 1, "JOUST": 1},
    },
    "7ingyu": {
        "total_moves": 1,
        "total_winning_moves": 0,
        "total_invalid_guesses": 1,
        "first_move_made": "2024-03-11",
        "most_recent_move": "2024-03-11",
        "guess_history": {"COEST": 1},
    },
    "emilyvictany": {
        "total_moves": 8,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-11",
        "most_recent_move": "2024-03-13",
        "guess_history": {
            "ADIEU": 1,
            "LASER": 1,
            "WATER": 1,
            "CATER": 1,
            "HATER": 1,
            "MATER": 1,
            "POISE": 1,
            "PRISM": 1,
        },
    },
    "KamronP23": {
        "total_moves": 1,
        "total_winning_moves": 0,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-11",
        "most_recent_move": "2024-03-11",
        "guess_history": {"SWEAR": 1},
    },
    "angelajfisher": {
        "total_moves": 6,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-12",
        "most_recent_move": "2024-03-12",
        "guess_history": {
            "TRACK": 1,
            "BRINE": 1,
            "PROMO": 1,
            "GROSS": 1,
            "GROWL": 1,
            "GROWN": 1,
        },
    },
    "JohnathanNiles": {
        "total_moves": 5,
        "total_winning_moves": 2,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-14",
        "most_recent_move": "2024-03-14",
        "guess_history": {"NASTY": 1, "SANDY": 1, "SNOWY": 1, "OVERT": 1, "HOVER": 1},
    },
    "Deafsnivz": {
        "total_moves": 1,
        "total_winning_moves": 0,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-14",
        "most_recent_move": "2024-03-14",
        "guess_history": {"AUDIO": 1},
    },
    "thejoshchow": {
        "total_moves": 3,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-14",
        "most_recent_move": "2024-03-14",
        "guess_history": {"CLOSE": 1, "FROGS": 1, "GLOSS": 1},
    },
    "amypirro": {
        "total_moves": 1,
        "total_winning_moves": 0,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-15",
        "most_recent_move": "2024-03-15",
        "guess_history": {"SNAKE": 1},
    },
    "dreramirez91": {
        "total_moves": 3,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-18",
        "most_recent_move": "2024-03-18",
        "guess_history": {"AUDIO": 1, "SHADE": 1, "SPADE": 1},
    },
    "aleetaing": {
        "total_moves": 4,
        "total_winning_moves": 1,
        "total_invalid_guesses": 0,
        "first_move_made": "2024-03-19",
        "most_recent_move": "2024-03-19",
        "guess_history": {"CRATE": 1, "FRAUD": 1, "DRAMA": 1, "DRANK": 1},
    },
}
