name: "Wordle"

on:
  issues:
    types: [opened]

jobs:
  wordle-guess:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'wordleguess|')
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Handle Move
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_USER: ${{ github.event.issue.user.login }}
        DISALLOWED_WORDS: ${{ vars.DISALLOWED_WORDS }}
        POSSIBLE_WORDS: ${{ vars.POSSIBLE_WORDS }}
      run: |
        python wordle/main.py
        echo 'the script ran'
        black wordle/
        echo 'black ran'

    - name: Commit Files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add .
        if [-z "$(git status --porcelain)"]; then
          echo "::set-output name=push::false"
        else
          git commit -m "wordle move updated" -a
          echo "::set-output name=push::true"
        fi
      shell: bash

    - name: Push Changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add in Waka Time
      uses: athul/waka-readme@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        TIME_RANGE: last_7_days
        SHOW_TOTAL: true
        SHOW_TITLE: true
        SHOW_TIME: true

    - name: Close Issue
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh issue close ${{github.event.issue.number}} -c "Thank you for playing!"
